name: (Monorepo - NodeJS and ReactJS) PR secure pipeline

# Policies run job in branches
on:
  workflow_call:
    inputs:
      # validate_branch
      runner_image_job_validate:
        description: 'Declare image runner to steps'
        required: true
        type: string
      action_harden_version:
        description: 'Version of actions/harden-runner to use'
        required: true
        default: 'v2'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Workflow reference => (Global - DevSecOps) Source validate PRs
  validate_branch:
    uses: ./.github/workflows/validate/source-validate-pr.yml
    with:
      call_runner_image: "${{ inputs.runner_image_job_validate }}"
      call_action_harden_version: "${{ inputs.action_harden_version }}"