name: (Monorepo - NodeJS and ReactJS) pipeline base CI

# Policies run job in branches
on:
  workflow_call:
    inputs:
      # Globals
      globals_node_version:
        description: 'Version of nodeJS to use'
        required: true
        type: string
      globals_package_manager:
        description: 'Declare the package manager as used, yarn or npm'
        required: true
        type: string
      globals_runner_image:
        description: 'Declare runner image to steps'
        required: true
        type: string

      # install_deps
      job_install_deps_install_args:
        description: 'Arguments of install to use'
        required: false
        default: "install"
        type: string

      # build_app
      job_build_app_path_compress_build:
        description: 'Path of build to compress'
        required: false
        default: "build"
        type: string
      job_build_app_build_args:
        description: 'Arguments of build to use'
        required: true
        type: string

      # build_image
      job_build_image_path_extract_build:
        description: 'Path to extract the build'
        required: false
        default: "./"
        type: string

jobs:
  # Workflow reference => (Monorepo - NodeJS and ReactJS) Install deps and Lint
  install_deps:
    name: "DevSecOps - Dependencies install"
    uses: ./.github/workflows/install.yml
    with:
      reusable_runner_image: "${{ inputs.globals_runner_image }}"
      reusable_package_manager: "${{ inputs.globals_package_manager }}"
      reusable_node_version: "${{ inputs.globals_node_version }}"

  # Workflow reference => (Monorepo - NodeJS and ReactJS) Build app
  build_app:
    name: "DevSecOps - Build App"
    uses: ./.github/workflows/build.yml
    with:
      reusable_runner_image: "${{ inputs.globals_runner_image }}"
      reusable_package_manager: "${{ inputs.globals_package_manager }}"
      reusable_node_version: "${{ inputs.globals_node_version }}"
      reusable_build_args: "${{ inputs.job_build_app_build_args }}"
      reusable_build_path: "${{ inputs.job_build_app_build_path }}"
    needs:
      - install_deps

  # Workflow reference => (Monorepo - NodeJS and ReactJS) Build image
  build_image:
    name: "DevSecOps - Build Image"
    uses: ./.github/workflows/build-image.yml
    with:
      reusable_runner_image: "${{ inputs.globals_runner_image }}"
      reusable_package_manager: "${{ inputs.globals_package_manager }}"
      reusable_path_extract_build: "${{ inputs.job_build_image_path_extract_build }}"
    needs:
      - build_app