# Name workflow in pipeline
name: (Monorepo - NodeJS and ReactJS) Build app

# Workflow sharing policy
on:
  workflow_call:
    inputs:
      reusable_runner_image:
        description: 'Declare runner image to steps'
        required: true
        type: string
      reusable_package_manager:
        description: 'Declare the package manager as used, yarn or npm'
        required: true
        type: string
      reusable_node_version:
        description: 'Version of nodeJS to use'
        required: true
        type: string
      reusable_path_compress_build:
        description: 'Path of build to compress'
        required: false
        type: string
      reusable_build_args:
        description: 'Arguments of build to use'
        required: true
        type: string

jobs:
  # Clean and checkout repositories. Clean workspace is enabled by default
  reusable_build_app:
    name: Code build
    runs-on: ${{ inputs.reusable_runner_image }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: use node.js ${{ inputs.reusable_node_version }} (npm)
        if: ${{ inputs.reusable_package_manager == 'npm' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.reusable_node_version }}
          cache: npm

      - name: use node.js ${{ inputs.reusable_node_version }} (yarn)
        if: ${{ inputs.reusable_package_manager == 'yarn' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.reusable_node_version }}
          cache: yarn

      - name: Restore cache dependencies (npm)
        if: ${{ inputs.reusable_package_manager == 'npm' }}
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ github.run_id }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.ref }}-${{ github.run_id }}-npm-

      - name: Restore cache dependencies (yarn)
        if: ${{ inputs.reusable_package_manager == 'yarn' }}
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ github.run_id }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ github.ref }}-${{ github.run_id }}-yarn-

      - name: Build (npm)
        if: ${{ inputs.reusable_package_manager == 'npm' }}
        run: |
          npm ${{ inputs.reusable_build_args }}
          tar -czf build.tar.gz ${{ inputs.reusable_path_compress_build }}

      - name: Build (yarn)
        if: ${{ inputs.reusable_package_manager == 'yarn' }}
        run: |
          yarn ${{ inputs.reusable_build_args }}
          tar -czf build.tar.gz ${{ inputs.reusable_path_compress_build }}

      - name: Upload artifact build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }}-build-${{ github.sha }}
          path: build.tar.gz
          retention-days: 1