# Name workflow in pipeline
name: (Monorepo - NodeJS and ReactJS) Build image

# Workflow sharing policy
on:
  workflow_call:
    inputs:
      reusable_runner_image:
        description: 'Declare runner name to steps'
        required: true
        type: string
      reusable_package_manager:
        description: 'Declare the package manager as used, yarn or npm'
        required: true
        type: string

jobs:
  # Clean and checkout repositories. Clean workspace is enabled by default
  reusable_build_image:
    name: Build container image
    runs-on: ${{ inputs.reusable_runner_image }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact build
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.run_id }}-build-${{ github.sha }}

      - name: Extract build (npm)
        run: |
          tar -xzf build.tar.gz

      - name: Install Buildah
        run: |
          wget https://github.com/containers/buildah/releases/latest/download/buildah-linux-amd64 -O buildah
          chmod +x buildah
          sudo mv buildah /usr/local/bin/

      - name: Build image
        run: |
          buildah --storage-driver vfs bud --format docker -t ${{ github.repository }}:latest .

      - name: Save image
        run: |
          buildah push --storage-driver vfs localhost/${{ github.repository }}:latest oci-archive:image-app.tar

      - name: Upload artifact image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }}-image-${{ github.sha }}
          path: image-app.tar
          retention-days: 1