# Name workflow in pipeline
name: (Monorepo - NodeJS and ReactJS) Build app

# Workflow sharing policy
on:
  workflow_call:
    inputs:
      reusable_runner_image:
        description: 'Declare image runner to steps'
        required: true
        type: string

jobs:
  # Clean and checkout repositories. Clean workspace is enabled by default
  reusable_build_app:
    name: Code build
    runs-on: ${{ inputs.reusable_runner_image }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v4