name: (Monorepo - NodeJS and ReactJS) pipeline base CI

# Policies run job in branches
on:
  workflow_call:
    inputs:
      # install_deps
      runner_image_job_install_deps:
        description: 'Declare image runner to steps'
        required: true
        type: string

      package_manager_job_install_deps:
        description: 'Declare image runner to steps'
        required: true
        type: string

      node_version_install_deps:
        description: 'Version of nodeJS to use'
        required: true
        type: string

      # build_app
      runner_image_job_build_app:
        description: 'Declare image runner to steps'
        required: true
        type: string

jobs:
  # # Workflow reference => (Global - DevSecOps) Notify status pipeline
  # notify_init:
  #   uses: ./.github/workflows/validate/notify-status.yml
  #   with:
  #     call_runner_image: "${{ inputs.runner_image_job_notify }}"
  #     call_action_checkout_version: "${{ inputs.action_checkout_version }}"
  #     call_action_harden_version: "${{ inputs.action_harden_version }}"

  # Workflow reference => (Monorepo - NodeJS and ReactJS) Install deps and Lint
  install_deps:
    name: "DevSecOps - Dependencies install"
    uses: ./.github/workflows/install.yml
    with:
      reusable_runner_image: "${{ inputs.runner_image_job_install_deps }}"
      reusable_package_manager: "${{ inputs.package_manager_job_install_deps }}"
      reusable_node_version: "${{ inputs.node_version_install_deps }}"

  # Workflow reference => (Monorepo - NodeJS and ReactJS) Build app
  build_app:
    name: "DevSecOps - Build App"
    uses: ./.github/workflows/build.yml
    with:
      reusable_runner_image: "${{ inputs.runner_image_job_build_app }}"
    needs:
      - install_deps